<a href="https://colab.research.google.com/github/Deboraj-roy/-mental-health-data-analyst/blob/main/Experiment_of_Chi_Square_Test_Copy_of_Hypothesis_Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Chi-Square Test- 

The test is applied when you have two categorical variables from a single population. It is used to determine whether there is a significant association between the two variables.

In [70]:
import scipy.stats as stats

In [71]:

import seaborn as sns
import pandas as pd
import numpy as np
dataset=sns.load_dataset('tips')

# dataset=sns.load_dataset('tips')
dataset = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Student Mental health (updated).csv")


In [72]:
dataset.head()

Timestamp Choose your gender   Age What is your course?  \
0  8/7/2020 12:02             Female  18.0          Engineering   
1  8/7/2020 12:04               Male  21.0    Islamic education   
2  8/7/2020 12:05               Male  19.0                  BIT   
3  8/7/2020 12:06             Female  22.0                 Laws   
4  8/7/2020 12:13               Male  23.0         Mathemathics   

  Your current year of Study CGPA Category Marital status  \
0                     year 1       Average             No   
1                     year 2       Average             No   
2                     Year 1       Average             No   
3                     year 3       Average            Yes   
4                     year 4       Average             No   

  Do you have Depression? Do you have Anxiety? Do you have Panic attack?  \
0                     Yes                   No                       Yes   
1                      No                  Yes                        No   
2                     Yes                  Yes                       Yes   
3                     Yes                   No                        No   
4                      No                   No                        No   

  Did you seek any specialist for a treatment?  
0                                           No  
1                                           No  
2                                           No  
3                                           No  
4                                           No

In [73]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [74]:
dataset_table=pd.crosstab(dataset['Choose your gender'],dataset['CGPA Category'])
print(dataset_table)

CGPA Category       Average  Bad  Excellent  Fail
Choose your gender                               
Female                   29    4         39     3
Male                     14    0          9     3


In [75]:
dataset_table.values 

array([[29,  4, 39,  3],
       [14,  0,  9,  3]])

In [76]:
#Observed Values
Observed_Values = dataset_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[29  4 39  3]
 [14  0  9  3]]


In [77]:
val=stats.chi2_contingency(dataset_table)

In [78]:
val

(5.506291741204532,
 0.13826278552132423,
 3,
 array([[31.93069307,  2.97029703, 35.64356436,  4.45544554],
        [11.06930693,  1.02970297, 12.35643564,  1.54455446]]))

In [79]:
Expected_Values=val[3]

In [80]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_columns=len(dataset_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [81]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [82]:
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 2.431580202742994


In [83]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [84]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.11891297343411045
Significance level:  0.05
Degree of Freedom:  1
p-value: 0.11891297343411045


In [85]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Retain H0,There is no relationship between 2 categorical variables
Retain H0,There is no relationship between 2 categorical variables


## T Test

A t-test is a type of inferential statistic which is used to determine if there is a significant difference between the means of two groups which may be related in certain features

T-test has 2 types : 1. one sampled t-test 2. two-sampled t-test.

##  One-sample T-test with Python

The test will tell us whether means of the sample and the population are different

![image.png](attachment:image.png)

In [86]:
ages=[10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]

In [87]:
len(ages)

32

In [88]:
import numpy as np
ages_mean=np.mean(ages)
print(ages_mean)

30.34375


In [89]:
## Lets take sample

sample_size=10
age_sample=np.random.choice(ages,sample_size)

In [90]:
age_sample

array([35, 43, 28, 70, 26, 55, 20, 16, 27, 16])

In [91]:
from scipy.stats import ttest_1samp

In [92]:
ttest,p_value=ttest_1samp(age_sample,30)

In [93]:
print(p_value)

0.5354991559663527


In [94]:
if p_value < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

we are accepting null hypothesis


## Some More Examples
Consider the age of students in a college and in Class A

In [95]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math
np.random.seed(6)
school_ages=stats.poisson.rvs(loc=18,mu=35,size=1500)
classA_ages=stats.poisson.rvs(loc=18,mu=30,size=60)


In [96]:
classA_ages.mean()

46.9

In [97]:
_,p_value=stats.ttest_1samp(a=classA_ages,popmean=school_ages.mean())

In [98]:
p_value

1.139027071016194e-13

In [99]:
school_ages.mean()

53.303333333333335

In [100]:
if p_value < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

 we are rejecting null hypothesis


## Two-sample T-test With Python
The Independent Samples t Test or 2-sample t-test compares the means of two independent groups in order to determine whether there is statistical evidence that the associated population means are significantly different. The Independent Samples t Test is a parametric test. This test is also known as: Independent t Test

![image.png](attachment:image.png)

In [101]:
np.random.seed(12)
ClassB_ages=stats.poisson.rvs(loc=18,mu=33,size=60)
ClassB_ages.mean()

50.63333333333333