<a href="https://colab.research.google.com/github/Deboraj-roy/-mental-health-data-analyst/blob/main/Final_of_Classifications_Clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [99]:
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder 

# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Weka/data/CGPA.csv")

# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

# Split the dataset into training and testing sets
X = df.drop(["CGPA Category"], axis=1)
y = df["CGPA Category"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the SVM model on the training data
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("SVM CGPA Accuracy:", accuracy)

SVM CGPA Accuracy: 0.2857142857142857


In [100]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [101]:
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder 

# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Weka/data/Marital-status.csv")

# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

# Split the dataset into training and testing sets
X = df.drop(["Marital status"], axis=1)
y = df["Marital status"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the SVM model on the training data
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("SVM Marital-status Accuracy:", accuracy)

SVM Marital-status Accuracy: 0.9047619047619048


In [102]:
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder 

# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Weka/data/Current-year-of-Study.csv")

# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

# Split the dataset into training and testing sets
X = df.drop(["Your current year of Study"], axis=1)
y = df["Your current year of Study"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the SVM model on the training data
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("SVM Current-year-of-Study Accuracy:", accuracy)

SVM Current-year-of-Study Accuracy: 0.47619047619047616


In [103]:
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder 

# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Weka/data/depression.csv")

# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

# Split the dataset into training and testing sets
X = df.drop(["Do you have Depression?"], axis=1)
y = df["Do you have Depression?"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the SVM model on the training data
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("SVM Depression Accuracy:", accuracy)

SVM Depression Accuracy: 0.6666666666666666


In [104]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder 
from sklearn.metrics import accuracy_score 

# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Weka/data/CGPA.csv")

# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

# Split the data into features (X) and target (y)
X = df.drop("CGPA Category", axis=1)
y = df["CGPA Category"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Train a Naive Bayes model
model = CategoricalNB()
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Naive Bayes model CGPA Accuracy: ", accuracy)

Naive Bayes model CGPA Accuracy:  0.42857142857142855


In [105]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score  
from sklearn.preprocessing import LabelEncoder 

# Load your categorical dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/CGPA.csv')

# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])


# Split the data into features (X) and target (y)
X = df.drop("CGPA Category", axis=1)
y = df["CGPA Category"]


# Split the data into training and testing sets
# train_data, test_data, train_labels, test_labels = train_test_split(df.drop('CGPA Category', axis=1), df['CGPA Category'], test_size=0.2)
train_data, test_data, train_labels, test_labels = train_test_split(X, y, test_size=0.2)

# Train the J48 classifier on the training data
j48 = DecisionTreeClassifier(criterion='entropy')
j48.fit(train_data, train_labels)

# Make predictions on the test data
predictions = j48.predict(test_data)

# Evaluate the accuracy of the model
accuracy = accuracy_score(test_labels, predictions)
print("J48 CGPA Accuracy:", accuracy)

J48 CGPA Accuracy: 0.47619047619047616


In [106]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/CGPA.csv')


# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])


# Split the dataset into features (X) and labels (y)
X = df.drop('CGPA Category', axis=1)
y = df['CGPA Category']

# Encode the categorical labels as integers
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

# Convert the integer-encoded labels to one-hot encodings
y_one_hot = to_categorical(y_encoded)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.2, random_state=42)

# Build the neural network model
model = Sequential()
model.add(Dense(32, input_dim=X.shape[1], activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(y_one_hot.shape[1], activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=32, verbose=0)

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Artificial neural network CGPA Test accuracy:', test_accuracy)

Artificial neural network CGPA Test accuracy: 0.2857142984867096


In [107]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/Marital-status.csv')


# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])


# Split the dataset into features (X) and labels (y)
X = df.drop('Marital status', axis=1)
y = df['Marital status']

# Encode the categorical labels as integers
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

# Convert the integer-encoded labels to one-hot encodings
y_one_hot = to_categorical(y_encoded)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.2, random_state=42)

# Build the neural network model
model = Sequential()
model.add(Dense(32, input_dim=X.shape[1], activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(y_one_hot.shape[1], activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=32, verbose=0)

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Artificial neural network Marital status Test accuracy:', test_accuracy)

Artificial neural network Marital status Test accuracy: 0.9047619104385376


In [108]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder 
from sklearn.metrics import accuracy_score 

# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Weka/data/Marital-status.csv")

# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

# Split the data into features (X) and target (y)
X = df.drop("Marital status", axis=1)
y = df["Marital status"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Train a Naive Bayes model
model = CategoricalNB()
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Naive Bayes Marital status Accuracy: ", accuracy)


Naive Bayes Marital status Accuracy:  0.8571428571428571


In [109]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score  
from sklearn.preprocessing import LabelEncoder 

# Load your categorical dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/Marital-status.csv')

# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])


# Split the data into features (X) and target (y)
X = df.drop("Marital status", axis=1)
y = df["Marital status"]


# Split the data into training and testing sets
# train_data, test_data, train_labels, test_labels = train_test_split(df.drop('CGPA Category', axis=1), df['CGPA Category'], test_size=0.2)
train_data, test_data, train_labels, test_labels = train_test_split(X, y, test_size=0.2)

# Train the J48 classifier on the training data
j48 = DecisionTreeClassifier(criterion='entropy')
j48.fit(train_data, train_labels)

# Make predictions on the test data
predictions = j48.predict(test_data)

# Evaluate the accuracy of the model
accuracy = accuracy_score(test_labels, predictions)
print("J48 Marital status Accuracy:", accuracy)

J48 Marital status Accuracy: 1.0


In [110]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder 
from sklearn.metrics import accuracy_score 

# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Weka/data/Current-year-of-Study.csv")

# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

# Split the data into features (X) and target (y)
X = df.drop("Your current year of Study", axis=1)
y = df["Your current year of Study"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Train a Naive Bayes model
model = CategoricalNB()
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Naive Bayes Current-year-of-Study Accuracy: ", accuracy)


Naive Bayes Current-year-of-Study Accuracy:  0.6190476190476191


In [111]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/Current-year-of-Study.csv')


# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])


# Split the dataset into features (X) and labels (y)
X = df.drop('Your current year of Study', axis=1)
y = df['Your current year of Study']

# Encode the categorical labels as integers
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

# Convert the integer-encoded labels to one-hot encodings
y_one_hot = to_categorical(y_encoded)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.2, random_state=42)

# Build the neural network model
model = Sequential()
model.add(Dense(32, input_dim=X.shape[1], activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(y_one_hot.shape[1], activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=32, verbose=0)

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Artificial neural network Your current year of Study Test accuracy:', test_accuracy)

Artificial neural network Your current year of Study Test accuracy: 0.4761904776096344


In [112]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score  
from sklearn.preprocessing import LabelEncoder 

# Load your categorical dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/Current-year-of-Study.csv')

# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])


# Split the data into features (X) and target (y)
X = df.drop("Your current year of Study", axis=1)
y = df["Your current year of Study"]


# Split the data into training and testing sets
# train_data, test_data, train_labels, test_labels = train_test_split(df.drop('CGPA Category', axis=1), df['CGPA Category'], test_size=0.2)
train_data, test_data, train_labels, test_labels = train_test_split(X, y, test_size=0.2)

# Train the J48 classifier on the training data
j48 = DecisionTreeClassifier(criterion='entropy')
j48.fit(train_data, train_labels)

# Make predictions on the test data
predictions = j48.predict(test_data)

# Evaluate the accuracy of the model
accuracy = accuracy_score(test_labels, predictions)
print("J48 Your current year of Study Accuracy:", accuracy)

J48 Your current year of Study Accuracy: 0.38095238095238093


In [113]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder 
from sklearn.metrics import accuracy_score 

# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Weka/data/depression.csv")

# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

# Split the data into features (X) and target (y)
X = df.drop("Do you have Depression?", axis=1)
y = df["Do you have Depression?"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Train a Naive Bayes model
model = CategoricalNB()
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Naive Bayes model Depression Accuracy: ", accuracy)

Naive Bayes model Depression Accuracy:  0.9047619047619048


In [114]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/depression.csv')


# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])


# Split the dataset into features (X) and labels (y)
X = df.drop('Do you have Depression?', axis=1)
y = df['Do you have Depression?']

# Encode the categorical labels as integers
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

# Convert the integer-encoded labels to one-hot encodings
y_one_hot = to_categorical(y_encoded)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.2, random_state=42)

# Build the neural network model
model = Sequential()
model.add(Dense(32, input_dim=X.shape[1], activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(y_one_hot.shape[1], activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=32, verbose=0)

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Artificial neural network Depression Test accuracy:', test_accuracy)

Artificial neural network Depression Test accuracy: 0.6666666865348816


In [115]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score  
from sklearn.preprocessing import LabelEncoder 

# Load your categorical dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/depression.csv')

# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])


# Split the data into features (X) and target (y)
X = df.drop("Do you have Depression?", axis=1)
y = df["Do you have Depression?"]


# Split the data into training and testing sets
# train_data, test_data, train_labels, test_labels = train_test_split(df.drop('CGPA Category', axis=1), df['CGPA Category'], test_size=0.2)
train_data, test_data, train_labels, test_labels = train_test_split(X, y, test_size=0.2)

# Train the J48 classifier on the training data
j48 = DecisionTreeClassifier(criterion='entropy')
j48.fit(train_data, train_labels)

# Make predictions on the test data
predictions = j48.predict(test_data)

# Evaluate the accuracy of the model
accuracy = accuracy_score(test_labels, predictions)
print("J48 Depression Accuracy:", accuracy)

J48 Depression Accuracy: 0.7619047619047619


# Random forest model test with categorical dataset using python

Sure, I can give you an example of how to test a random forest model with a categorical dataset in Python using scikit-learn.

First, you need to import the necessary libraries:

Next, you need to load your categorical dataset. Let's assume your dataset is stored in a CSV file named "my_dataset.csv". You can load it into a pandas DataFrame using the read_csv() function:
Now, you need to split your dataset into training and testing sets. You can use the train_test_split() function for this:

Here, we are splitting the dataset into training and testing sets with a test size of 20% and a random state of 42 (for reproducibility).

Next, you can create a random forest classifier and fit it on the training data:

Finally, you can use the trained model to make predictions on the test set and evaluate its performance using the accuracy score:

That's it! This is a basic example of how to test a random forest model with a categorical dataset in Python using scikit-learn. You can customize the code according to your specific needs.


In [116]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data/CGPA.csv')


# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])


X = df.drop('CGPA Category', axis=1) # assuming the target variable is named "target_variable"
y = df['CGPA Category']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)


print("Random Forest Classifier CGPA Accuracy:", accuracy)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))




Random Forest Classifier CGPA Accuracy: 0.6190476190476191
Confusion Matrix:
 [[10  0  3  0]
 [ 0  0  1  0]
 [ 3  0  3  0]
 [ 1  0  0  0]]


In [117]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/Current-year-of-Study.csv')


# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])


X = df.drop('Your current year of Study', axis=1) # assuming the target variable is named "target_variable"
y = df['Your current year of Study']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)


print("Random Forest Classifier Your current year of Study Accuracy:", accuracy)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))




Random Forest Classifier Your current year of Study Accuracy: 0.47619047619047616
Confusion Matrix:
 [[9 0 0 0]
 [6 0 2 0]
 [2 0 1 0]
 [1 0 0 0]]


In [118]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/Marital-status.csv')


# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])


X = df.drop('Marital status', axis=1) # assuming the target variable is named "target_variable"
y = df['Marital status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)


print("Random Forest Classifier Marital status Accuracy:", accuracy)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))




Random Forest Classifier Marital status Accuracy: 0.9047619047619048
Confusion Matrix:
 [[17  1]
 [ 1  2]]


In [119]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/depression.csv')


# Encode categorical variables into numerical values
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])


X = df.drop('Do you have Depression?', axis=1) # assuming the target variable is named "target_variable"
y = df['Do you have Depression?']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)


print("Random Forest Classifier Depression Accuracy:", accuracy)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))




Random Forest Classifier Depression Accuracy: 0.6666666666666666
Confusion Matrix:
 [[12  1]
 [ 6  2]]




```
# This is formatted as code
```

# New Section KNN

To test a KNN model with categorical dataset in Python, you can follow these general steps:

Prepare your dataset: First, you need to prepare your categorical dataset. This can include loading the data from a CSV file, encoding the categorical variables, and splitting the dataset into training and testing sets.

Import the necessary libraries: You will need to import the necessary libraries for data preprocessing, building the KNN model, and evaluating its performance. Some common libraries for this task are pandas, scikit-learn, and numpy.

Preprocess the data: You will need to preprocess the data by scaling the numerical variables and encoding the categorical variables using techniques such as one-hot encoding or label encoding.

Build the KNN model: You can build a KNN model using scikit-learn's KNeighborsClassifier function. You will need to specify the number of neighbors to consider, as well as any other hyperparameters you want to tune.

Train the KNN model: You can train the KNN model using the fit() method of the KNeighborsClassifier object. This will fit the model to the training data.

Test the KNN model: You can test the KNN model using the predict() method of the KNeighborsClassifier object. This will predict the class labels for the test data.

Evaluate the KNN model: You can evaluate the performance of the KNN model using metrics such as accuracy, precision, recall, and F1 score. You can use scikit-learn's classification_report() function to generate a report with these metrics.

Here is some example code that demonstrates these steps:

In [212]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/CGPA.csv')

# Split the dataset into training and testing sets
X = df.drop('CGPA Category', axis=1)
y = df['CGPA Category']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Encode the categorical variables using label encoding
le = LabelEncoder()
for col in X_train.select_dtypes(include='object').columns:
    X_train[col] = le.fit_transform(X_train[col])
    X_test[col] = le.transform(X_test[col])

# Scale the numerical variables using standard scaling
scaler = StandardScaler()
for col in X_train.select_dtypes(include='number').columns:
    X_train[col] = scaler.fit_transform(X_train[[col]])
    X_test[col] = scaler.transform(X_test[[col]])

# Build the KNN model
k = 10
knn = KNeighborsClassifier(n_neighbors=k)

# Train the KNN model
knn.fit(X_train, y_train)

# Test the KNN model
y_pred = knn.predict(X_test)

# Evaluate the KNN model
print(classification_report(y_test, y_pred))


accuracy = accuracy_score(y_test, y_pred)
print("KNN CGPA Accuracy:", accuracy)


              precision    recall  f1-score   support

     Average       0.71      0.77      0.74        13
         Bad       0.00      0.00      0.00         1
   Excellent       0.43      0.50      0.46         6
        Fail       0.00      0.00      0.00         1

    accuracy                           0.62        21
   macro avg       0.29      0.32      0.30        21
weighted avg       0.56      0.62      0.59        21

KNN CGPA Accuracy: 0.6190476190476191


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [211]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/Current-year-of-Study.csv')

# Split the dataset into training and testing sets
X = df.drop('Your current year of Study', axis=1)

y =  df['Your current year of Study']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Encode the categorical variables using label encoding
le = LabelEncoder()
for col in X_train.select_dtypes(include='object').columns:
    X_train[col] = le.fit_transform(X_train[col])
    X_test[col] = le.transform(X_test[col])

# Scale the numerical variables using standard scaling
scaler = StandardScaler()
for col in X_train.select_dtypes(include='number').columns:
    X_train[col] = scaler.fit_transform(X_train[[col]])
    X_test[col] = scaler.transform(X_test[[col]])

# Build the KNN model
k = 10
knn = KNeighborsClassifier(n_neighbors=k)

# Train the KNN model
knn.fit(X_train, y_train)

# Test the KNN model
y_pred = knn.predict(X_test)

# Evaluate the KNN model
print(classification_report(y_test, y_pred))


accuracy = accuracy_score(y_test, y_pred)
print("KNN Current year of Study Accuracy:", accuracy)


              precision    recall  f1-score   support

      Year 1       0.50      1.00      0.67         9
      Year 2       0.00      0.00      0.00         8
      Year 3       0.33      0.33      0.33         3
      Year 4       0.00      0.00      0.00         1

    accuracy                           0.48        21
   macro avg       0.21      0.33      0.25        21
weighted avg       0.26      0.48      0.33        21

KNN Current year of Study Accuracy: 0.47619047619047616


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [210]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/Marital-status.csv')

# Split the dataset into training and testing sets

X = df.drop('Marital status', axis=1)

y =  df['Marital status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Encode the categorical variables using label encoding
le = LabelEncoder()
for col in X_train.select_dtypes(include='object').columns:
    X_train[col] = le.fit_transform(X_train[col])
    X_test[col] = le.transform(X_test[col])

# Scale the numerical variables using standard scaling
scaler = StandardScaler()
for col in X_train.select_dtypes(include='number').columns:
    X_train[col] = scaler.fit_transform(X_train[[col]])
    X_test[col] = scaler.transform(X_test[[col]])

# Build the KNN model
k = 10
knn = KNeighborsClassifier(n_neighbors=k)

# Train the KNN model
knn.fit(X_train, y_train)

# Test the KNN model
y_pred = knn.predict(X_test)

# Evaluate the KNN model
print(classification_report(y_test, y_pred))


accuracy = accuracy_score(y_test, y_pred)
print("KNN Marital status Accuracy:", accuracy)


              precision    recall  f1-score   support

          No       0.89      0.94      0.92        18
         Yes       0.50      0.33      0.40         3

    accuracy                           0.86        21
   macro avg       0.70      0.64      0.66        21
weighted avg       0.84      0.86      0.84        21

KNN Marital status Accuracy: 0.8571428571428571


In [208]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Weka/data/depression.csv')

# Split the dataset into training and testing sets

X = df.drop('Do you have Depression?', axis=1)
y = df['Do you have Depression?']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Encode the categorical variables using label encoding
le = LabelEncoder()
for col in X_train.select_dtypes(include='object').columns:
    X_train[col] = le.fit_transform(X_train[col])
    X_test[col] = le.transform(X_test[col])

# Scale the numerical variables using standard scaling
scaler = StandardScaler()
for col in X_train.select_dtypes(include='number').columns:
    X_train[col] = scaler.fit_transform(X_train[[col]])
    X_test[col] = scaler.transform(X_test[[col]])

# Build the KNN model
k = 10
knn = KNeighborsClassifier(n_neighbors=k)

# Train the KNN model
knn.fit(X_train, y_train)

# Test the KNN model
y_pred = knn.predict(X_test)

# Evaluate the KNN model
print(classification_report(y_test, y_pred))


accuracy = accuracy_score(y_test, y_pred)
print("KNN Depression Accuracy:", accuracy)


              precision    recall  f1-score   support

          No       0.63      0.92      0.75        13
         Yes       0.50      0.12      0.20         8

    accuracy                           0.62        21
   macro avg       0.57      0.52      0.47        21
weighted avg       0.58      0.62      0.54        21

KNN Depression Accuracy: 0.6190476190476191
